language: minimal
services:
  - docker
install:
  - make stay@test build
  - make @test run CMD="idilic info"
  - make @prod run CMD="idilic info"
  - make @test run CMD="idilic info"
  - make @dev  run CMD="idilic info"
script: |
  make ct b t;
  make stay@dev ct b t;
  make @prod ct b;
  make ct b t;
  make @test ct b t;
