#!/bin/bash
set -eu;

while read -d $'\0' VAR; do
	[[ ! -z "$VAR" ]] && declare "$VAR";
done < <(make env SEP=-0);

echo Pushing $BRANCH;

[[ "$TARGET" == "test" ]] && set +x;

while read LINE; do echo $LINE | {
	IFS=":" read BRANCH TARGET

	echo "$BRANCH:$TARGET found in .publishing file. Ids is building & pushing now.";

	make TARGET=$TARGET;
	make TARGET=$TARGET push-images;

}; done < <(grep ^$BRANCH\: .publishing);
