#!/bin/bash

set -eu;

export $(make env | tr '\n' ' ');

[[ "$TARGET" == "dev" ]] ||  set -eux;

if grep -q ^$BRANCH\:$TARGET\$ .publishing; then

	echo "$BRANCH:$TARGET found in .publishing file. Ids is building & pushing now.";

	make TARGET=$TARGET;
	make TARGET=$TARGET push-images;

	exit 0;
fi

echo "Branch '$BRANCH' is not in the .publishing file.";
