#!/bin/bash
set -eu;

while read -d $'\0' VAR; do
	[[ ! -z "$VAR" ]] && declare "$VAR";
done < <(make @base env SEP=-0);

make @base b;

echo Pushing $BRANCH;

[[ "$TARGET" == "dev" ]] && set +x;

while read LINE; do echo $LINE | {
	IFS=":" read BRANCH TARGET

	echo "$BRANCH:$TARGET found in .publishing file. Ids is building & pushing now.";

	make @$TARGET build;
	make @$TARGET push-images;

}; done < <(grep ^$BRANCH\: .publishing);
