#!/bin/bash
set -eu;

while read -d $'\0' VAR; do
	[[ ! -z "$VAR" ]] && declare "$VAR";
done < <(make @base env SEP=-0);

[[ "$TARGET" == "dev" ]] && set +x;

PHP_ERROR=0;

git diff-index HEAD | grep "^:" | grep ".php" \
	| sed 's:.* [UAM][ \\''t]*\([^ \\''t]*\):\1:g' \
	| while read FILE; do \
		test -f $FILE || continue;
		echo Checking $FILE...;
		echo -ne "\t";
		php -l $FILE 2>&1;
		PHP_ERROR=$?;
	done;

set -eu;

[[ ! -z "$PHP_ERROR" ]] && ( \
	echo Please correct the above errors before committing. \
		exit $PHP_ERROR;\
	) \
	|| echo No php errors found.;

make @test t;

echo Committing to $BRANCH;
