#!/bin/bash

while read -d $'\0' VAR ; do declare "$VAR"; done < <(make env);

[[ "$TARGET" == "test" ]] && set +x;

PHP_ERROR=0;

git diff-index HEAD \
	| grep ".php"   \
	| grep "^:"     \
	| sed 's:.* [UAM][ \\''t]*\([^ \\''t]*\):\1:g' \
	| while read FILE; do \
		test -f $FILE || continue;
		echo Checking $FILE...;
		echo -ne "\t";
		php -l $FILE 2>&1;
		PHP_ERROR=$?;
	done;

set -eu;

[[ 0 -ne $PHP_ERROR ]] \
	&& echo Please correct the above errors before committing.;

exit $PHP_ERROR;
