 version: 2
 jobs:
   build:
     steps:
       - checkout
       - run: make @base ct b
       - run: make ct b t lt li
       - run: make stay@dev ct b lt li
       - run: make @prod ct b
       - run: make ct b
       - run: make @test ct b t
       - run: make stay@base ct b
       - run: make ct b
       - run: PHP=7.1 make @base ct b
       - run: PHP=7.1 make @dev ct b
       - run: PHP=7.1 make @prod ct b
       - run: PHP=7.1 make @test ct b
       - run: PHP=7.1 make @base ct b
       - run: PHP=7.1 make @test ct b t lt li
       - run: PHP=7.1 make stay@dev ct b lt li
       - run: PHP=7.1 make @prod ct b
       - run: PHP=7.1 make ct b
       - run: PHP=7.1 make @test ct b t
       - run: PHP=7.1 make stay@base ct b
       - run: PHP=7.1 make ct b
       - run: PHP=7.2 make @base ct b
       - run: PHP=7.2 make @dev ct b
       - run: PHP=7.2 make @prod ct b
       - run: PHP=7.2 make @test ct b
       - run: PHP=7.2 make @base ct b
       - run: PHP=7.2 make @test ct b t lt li
       - run: PHP=7.2 make stay@dev ct b lt li
       - run: PHP=7.2 make @prod ct b
       - run: PHP=7.2 make ct b
       - run: PHP=7.2 make @test ct b t
       - run: PHP=7.2 make stay@base ct b
       - run: PHP=7.2 make ct b
       - run: PHP=7.3 make @base ct b
       - run: PHP=7.3 make @dev ct b
       - run: PHP=7.3 make @prod ct b
       - run: PHP=7.3 make @test ct b
       - run: PHP=7.3 make @base ct b
       - run: PHP=7.3 make @test ct b t lt li
       - run: PHP=7.3 make stay@dev ct b lt li
       - run: PHP=7.3 make @prod ct b
       - run: PHP=7.3 make ct b
       - run: PHP=7.3 make @test ct b t
       - run: PHP=7.3 make stay@base ct b
       - run: PHP=7.3 make ct b
       - run: PHP=7.4 make @base ct b
       - run: PHP=7.4 make @dev ct b
       - run: PHP=7.4 make @prod ct b
       - run: PHP=7.4 make @test ct b
       - run: PHP=7.4 make @base ct b
       - run: PHP=7.4 make @test ct b t lt li
       - run: PHP=7.4 make stay@dev ct b lt li
       - run: PHP=7.4 make @prod ct b
       - run: PHP=7.4 make ct b
       - run: PHP=7.4 make @test ct b t
       - run: PHP=7.4 make stay@base ct b
       - run: PHP=7.4 make ct b

