version: 2.1

commands:
  install-composer:
    steps:
      - run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php7.4-cli php7.4-common php7.4-mbstring php7.4-intl php7.4-zip php7.4-bcmath php7.4-dom
          curl -s https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

  docker-permissions:
    steps:
      - run: |
          sudo chgrp docker /usr/bin/docker  /var/run/docker.sock
          sudo chmod    555 /usr/bin/docker  /var/run/docker.sock
          sudo usermod -aG docker $USER
          sudo find . -type d -exec chmod o-rwx  {} \;
          sudo find . -type f -exec chmod o-rwx  {} \;
          sudo find . -type d -exec chmod ug+rwx {} \;
          sudo find . -type f -exec chmod ug+rw  {} \;
          sudo find . -type f -exec chmod g+s    {} \;

workflows:
  version: 2

  build-test-push:
    jobs:
      - self-test
      - init-test
      - add-on-test
      - recursive-test-1
      - recursive-test-2
      - recursive-test-3
      - build-and-push:
          requires:
            - self-test
            - init-test
            - recursive-test-1
            - recursive-test-2
            - recursive-test-3
      - build-test-push-addons:
          requires:
            - add-on-test

  build-test-push_7-1:
    jobs:
      - self-test_7-1
      - init-test_7-1
      - add-on-test_7-1
      - recursive-test-1_7-1
      - recursive-test-2_7-1
      - recursive-test-3_7-1
      - build-and-push_7-1:
          requires:
            - self-test_7-1
            - init-test_7-1
            - recursive-test-1_7-1
            - recursive-test-2_7-1
            - recursive-test-3_7-1
      - build-test-push-addons_7-1:
          requires:
            - add-on-test_7-1

  build-test-push_7-2:
    jobs:
      - self-test_7-2
      - init-test_7-2
      - add-on-test_7-2
      - recursive-test-1_7-2
      - recursive-test-2_7-2
      - recursive-test-3_7-2
      - build-and-push_7-2:
          requires:
            - self-test_7-2
            - init-test_7-2
            - recursive-test-1_7-2
            - recursive-test-2_7-2
            - recursive-test-3_7-2
      - build-test-push-addons_7-2:
          requires:
            - add-on-test_7-2

  build-test-push_7-3:
    jobs:
      - self-test_7-3
      - init-test_7-3
      - add-on-test_7-3
      - recursive-test-1_7-3
      - recursive-test-2_7-3
      - recursive-test-3_7-3
      - build-and-push_7-3:
          requires:
            - self-test_7-3
            - init-test_7-3
            - recursive-test-1_7-3
            - recursive-test-2_7-3
            - recursive-test-3_7-3
      - build-test-push-addons_7-3:
          requires:
            - add-on-test_7-3

  build-test-push_7-4:
    jobs:
      - self-test_7-4
      - init-test_7-4
      - add-on-test_7-4
      - recursive-test-1_7-4
      - recursive-test-2_7-4
      - recursive-test-3_7-4
      - build-and-push_7-4:
          requires:
            - self-test_7-4
            - init-test_7-4
            - recursive-test-1_7-4
            - recursive-test-2_7-4
            - recursive-test-3_7-4
      - build-test-push-addons_7-4:
          requires:
            - add-on-test_7-4

jobs:
  init-test:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer create-project seanmorris/ids-project -s dev --remove-vcs
      - run: |
          cd ids-project \
          && composer require seanmorris/ids:dev-${CIRCLE_BRANCH} \
          && make @test start-bg test

  init-test_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer create-project seanmorris/ids-project -s dev --remove-vcs
      - run: |
          cd ids-project \
          && composer require seanmorris/ids:dev-${CIRCLE_BRANCH} \
          && PHP=7.1 make @test start-bg test

  init-test_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: composer create-project seanmorris/ids-project -s dev --remove-vcs
      - run: |
          cd ids-project \
          && composer require seanmorris/ids:dev-${CIRCLE_BRANCH} \
          && PHP=7.2 make @test start-bg test

  init-test_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer create-project seanmorris/ids-project -s dev --remove-vcs
      - run: |
          cd ids-project \
          && composer require seanmorris/ids:dev-${CIRCLE_BRANCH} \
          && PHP=7.3 make @test start-bg test

  init-test_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer create-project seanmorris/ids-project -s dev --remove-vcs
      - run: |
          cd ids-project \
          && composer require seanmorris/ids:dev-${CIRCLE_BRANCH} \
          && PHP=7.4 make @test start-bg test

  self-test:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: make @base ct b
      - run: make @dev ct b
      - run: make @prod ct b
      - run: make @test ct b
      - run: make @base ct b
      - run: make @test ct b t lt li
      - run: make stay@dev ct b lt li
      - run: make @prod ct b
      - run: make ct b
      - run: make @test ct b t
      - run: make stay@base ct b
      - run: make ct b

  self-test_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: PHP=7.1 make @base ct b
      - run: PHP=7.1 make @dev ct b
      - run: PHP=7.1 make @prod ct b
      - run: PHP=7.1 make @test ct b
      - run: PHP=7.1 make @base ct b
      - run: PHP=7.1 make @test ct b t lt li
      - run: PHP=7.1 make stay@dev ct b lt li
      - run: PHP=7.1 make @prod ct b
      - run: PHP=7.1 make ct b
      - run: PHP=7.1 make @test ct b t
      - run: PHP=7.1 make stay@base ct b
      - run: PHP=7.1 make ct b

  self-test_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: PHP=7.2 make @base ct b
      - run: PHP=7.2 make @dev ct b
      - run: PHP=7.2 make @prod ct b
      - run: PHP=7.2 make @test ct b
      - run: PHP=7.2 make @base ct b
      - run: PHP=7.2 make @test ct b t lt li
      - run: PHP=7.2 make stay@dev ct b lt li
      - run: PHP=7.2 make @prod ct b
      - run: PHP=7.2 make ct b
      - run: PHP=7.2 make @test ct b t
      - run: PHP=7.2 make stay@base ct b
      - run: PHP=7.2 make ct b

  self-test_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: PHP=7.3 make @base ct b
      - run: PHP=7.3 make @dev ct b
      - run: PHP=7.3 make @prod ct b
      - run: PHP=7.3 make @test ct b
      - run: PHP=7.3 make @base ct b
      - run: PHP=7.3 make @test ct b t lt li
      - run: PHP=7.3 make stay@dev ct b lt li
      - run: PHP=7.3 make @prod ct b
      - run: PHP=7.3 make ct b
      - run: PHP=7.3 make @test ct b t
      - run: PHP=7.3 make stay@base ct b
      - run: PHP=7.3 make ct b

  self-test_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: PHP=7.4 make @base ct b
      - run: PHP=7.4 make @dev ct b
      - run: PHP=7.4 make @prod ct b
      - run: PHP=7.4 make @test ct b
      - run: PHP=7.4 make @base ct b
      - run: PHP=7.4 make @test ct b t lt li
      - run: PHP=7.4 make stay@dev ct b lt li
      - run: PHP=7.4 make @prod ct b
      - run: PHP=7.4 make ct b
      - run: PHP=7.4 make @test ct b t
      - run: PHP=7.4 make stay@base ct b
      - run: PHP=7.4 make ct b

  recursive-test-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo make @test+make ct b run CMD="make @test test"

  recursive-test-1_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.1 make @test+make ct b run CMD="make @test test"

  recursive-test-1_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.2 make @test+make ct b run CMD="make @test test"

  recursive-test-1_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.3 make @test+make ct b run CMD="make @test test"

  recursive-test-1_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.4 make @test+make ct b run CMD="make @test test"

  recursive-test-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo make @test+inotify+make run CMD="make run CMD=\"make test\""

  recursive-test-2_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.1 make @test+make run CMD="make run CMD=\"make test\""

  recursive-test-2_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.2 make @test+make run CMD="make run CMD=\"make test\""

  recursive-test-2_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.3 make @test+make run CMD="make run CMD=\"make test\""

  recursive-test-2_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.4 make @test+make run CMD="make run CMD=\"make test\""

  recursive-test-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo make @test+make run CMD="make run CMD=\"make CMD=\\\"make test\\\"\""

  recursive-test-3_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.1 make @test+make run CMD="make run CMD=\"make CMD=\\\"make test\\\"\""

  recursive-test-3_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.2 make @test+make run CMD="make run CMD=\"make CMD=\\\"make test\\\"\""

  recursive-test-3_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.3 make @test+make run CMD="make run CMD=\"make CMD=\\\"make test\\\"\""

  recursive-test-3_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - docker-permissions
      - run: composer install
      - run: sudo PHP=7.4 make @test+make run CMD="make run CMD=\"make CMD=\\\"make test\\\"\""

  add-on-test:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: make @base+aptcache ct b
      - run: make @dev+aptcache+graylog+inotify ct b
      - run: make @test+aptcache ct b
      - run: make @test+aptcache+graylog+inotify ct t

  add-on-test_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: PHP=7.1 composer install
      - run: PHP=7.1 make @base+aptcache ct b
      - run: PHP=7.1 make @dev+aptcache+graylog+inotify ct b
      - run: PHP=7.1 make @test+aptcache ct b
      - run: PHP=7.1 make @test+aptcache+graylog+inotify ct t

  add-on-test_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: PHP=7.2 composer install
      - run: PHP=7.2 make @base+aptcache ct b
      - run: PHP=7.2 make @dev+aptcache+graylog+inotify ct b
      - run: PHP=7.2 make @test+aptcache ct b
      - run: PHP=7.2 make @test+aptcache+graylog+inotify ct t

  add-on-test_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: PHP=7.3 composer install
      - run: PHP=7.3 make @base+aptcache ct b
      - run: PHP=7.3 make @dev+aptcache+graylog+inotify ct b
      - run: PHP=7.3 make @test+aptcache ct b
      - run: PHP=7.3 make @test+aptcache+graylog+inotify ct t

  add-on-test_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: PHP=7.4 composer install
      - run: PHP=7.4 make @base+aptcache ct b
      - run: PHP=7.4 make @dev+aptcache+graylog+inotify ct b
      - run: PHP=7.4 make @test+aptcache ct b
      - run: PHP=7.4 make @test+aptcache+graylog+inotify ct t


  build-and-push:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: make @base ct b psi
      - run: make @dev  ct b psi
      - run: make @prod ct b psi
      - run: make @test ct b psi

  build-and-push_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.1 make @base ct b psi
      - run: PHP=7.1 make @dev  ct b psi
      - run: PHP=7.1 make @prod ct b psi
      - run: PHP=7.1 make @test ct b psi

  build-and-push_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.2 make @base ct b psi
      - run: PHP=7.2 make @dev  ct b psi
      - run: PHP=7.2 make @prod ct b psi
      - run: PHP=7.2 make @test ct b psi

  build-and-push_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.3 make @base ct b psi
      - run: PHP=7.3 make @dev  ct b psi
      - run: PHP=7.3 make @prod ct b psi
      - run: PHP=7.3 make @test ct b psi

  build-and-push_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.4 make @base ct b psi
      - run: PHP=7.4 make @dev  ct b psi
      - run: PHP=7.4 make @prod ct b psi
      - run: PHP=7.4 make @test ct b psi

  build-test-push-addons:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: composer install
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: make @base+aptcache ct b psi
      - run: make @dev+aptcache+graylog+inotify  ct b psi
      - run: make @prod+aptcache ct b psi
      - run: make @test+aptcache ct b psi

  build-test-push-addons_7-1:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.1 composer install
      - run: PHP=7.1 make @base+aptcache ct b psi
      - run: PHP=7.1 make @dev+aptcache+graylog+inotify ct b psi
      - run: PHP=7.1 make @test+aptcache ct b psi
      - run: PHP=7.1 make @prod+aptcache ct b psi

  build-test-push-addons_7-2:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.2 composer install
      - run: PHP=7.2 make @base+aptcache ct b psi
      - run: PHP=7.2 make @dev+aptcache+graylog+inotify ct b psi
      - run: PHP=7.2 make @test+aptcache ct b psi
      - run: PHP=7.2 make @prod+aptcache ct b psi

  build-test-push-addons_7-3:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.3 composer install
      - run: PHP=7.3 make @base+aptcache ct b psi
      - run: PHP=7.3 make @dev+aptcache+graylog+inotify ct b psi
      - run: PHP=7.3 make @test+aptcache ct b psi
      - run: PHP=7.3 make @prod+aptcache ct b psi

  build-test-push-addons_7-4:
    parallelism: 1
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-composer
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run: PHP=7.4 composer install
      - run: PHP=7.4 make @base+aptcache ct b psi
      - run: PHP=7.4 make @dev+aptcache+graylog+inotify ct b psi
      - run: PHP=7.4 make @test+aptcache ct b psi
      - run: PHP=7.4 make @prod+aptcache ct b psi
