apiVersion: batch/v1
kind: Job
metadata:
  name: updater
spec:
  template:
    spec:
      containers:
        - name: updater
          image: $REPO/$PROJECT.idilic:$TAG
          command: ['idilic', 'applySchemas', '1']
      restartPolicy: OnFailure
  backoffLimit: 4
