version: '2.4'

services:

  server:
    extends:
      file: ../../vendor/seanmorris/ids/infra/compose/base.yml
      service: server

  idilic:
    extends:
      file: ../../vendor/seanmorris/ids/infra/compose/base.yml
      service: idilic

  database:
    extends:
      file: ../../vendor/seanmorris/ids/infra/compose/base.yml
      service: database

volumes:
  schema:
    driver: local
