version: '2.4'

services:

  idilic:
    extends:
      file: base.yml
      service: idilic
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    environment:
      DHOST_IP: ${DHOST_IP}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  server:
    extends:
      file: base.yml
      service: server
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    environment:
      DHOST_IP: ${DHOST_IP}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  database:
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
