version: '2.4'

services:

  server:
    image: ${REPO}/ids.server:${TAG}
    ports: [ '80:80' ]
    restart: always
    depends_on:
        - database
    env_file:
      ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/server.dockerfile
    volumes:
      - ../../:/app
      - /tmp:/tmp

  idilic:
    image: ${REPO}/ids.idilic:${TAG}
    restart: on-failure
    depends_on:
        - database
    env_file:
      ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/idilic.dockerfile
    volumes:
      - ../../:/app
      - /tmp:/tmp

  database:
    image: mariadb:10.4.8-bionic
    restart: always
    ports: ['9996:3306']
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_USER:          test
      MYSQL_PASSWORD:      test
      MYSQL_DATABASE:      ids_schema
      MYSQL_ROOT_PASSWORD: test
    command: ['mysqld', '--character-set-server=utf8mb4']

volumes:
  schema:
    driver: "local"



  # idilic:
  #   image: ${REPO}/ids.idilic:${TAG}
  #   build:
  #     context: ../../
  #     dockerfile: infra/docker/idilic.dockerfile
  #   restart: on-failure
  #   volumes:
  #     - ../../:/app
  #     - /tmp:/tmp
