version: '2.4'

services:

  server:
    image: ${REPO}/${PROJECT}.server:${TAG}
    restart: always
    build:
      context: ../../
      dockerfile: infra/docker/server.dockerfile
      target: ${TARGET}

  idilic:
    image: ${REPO}/${PROJECT}.idilic:${TAG}
    restart: on-failure
    build:
      context: ../../
      dockerfile: infra/docker/idilic.dockerfile
      target: ${TARGET}

  database:
    image: mariadb:10.4.8-bionic
    restart: always
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_USER:          ${IDS_DATABASES_MAIN_USERNAME}
      MYSQL_PASSWORD:      ${IDS_DATABASES_MAIN_PASSWORD}
      MYSQL_DATABASE:      ${IDS_DATABASES_MAIN_DATABASE}
      MYSQL_PORT:          ${IDS_DATABASES_MAIN_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    command: ['mysqld', '--character-set-server=utf8mb4']

volumes:
  schema:
    driver: local
