version: '2.4'

services:

  idilic:
    image:   ${REPO}/${PROJECT}.idilic:${TAG}
    user:    ${D_UID}:${D_GID}
    restart: on-failure
    env_file:
      - ${MAIN_DLT}
      - ${MAIN_ENV}
      - ${TRGT_DLT}
      - ${TRGT_ENV}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:${DOCKER}
    build:
      context: ../../
      dockerfile: infra/docker/idilic.___gen.dockerfile
      target:  ${TARGET}
      network: bridge
      args:
        IDS_APT_PROXY_HOST: ${IDS_APT_PROXY_HOST}
        IDS_APT_PROXY_PORT: ${IDS_APT_PROXY_PORT}

  server:
    image:   ${REPO}/${PROJECT}.server:${TAG}
    user:    ${D_UID}:${D_GID}
    restart: always
    env_file:
      - ${MAIN_DLT}
      - ${MAIN_ENV}
      - ${TRGT_DLT}
      - ${TRGT_ENV}
    build:
      context: ../../
      dockerfile: infra/docker/server.___gen.dockerfile
      target:  ${TARGET}
      network: bridge
      args:
        IDS_APT_PROXY_HOST: ${IDS_APT_PROXY_HOST}
        IDS_APT_PROXY_PORT: ${IDS_APT_PROXY_PORT}

  database:
    command: ['mysqld', '--character-set-server=utf8mb4']
    image:   mysql:5.7.28
    restart: always
    volumes: ['schema:/var/lib/mysql']
    env_file:
      - ${MAIN_DLT}
      - ${MAIN_ENV}
      - ${TRGT_DLT}
      - ${TRGT_ENV}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER:     ${IDS_DATABASES_MAIN_USERNAME}
      MYSQL_PASSWORD: ${IDS_DATABASES_MAIN_PASSWORD}
      MYSQL_DATABASE: ${IDS_DATABASES_MAIN_DATABASE}
      MYSQL_TCP_PORT: ${IDS_DATABASES_MAIN_PORT}

volumes:
  schema:
    driver: local

networks:
  bridge: {}
