version: '2.4'

services:

  idilic:
    image: ${REPO}/${PROJECT}.idilic:${TAG}
    restart: on-failure
    env_file:
      ../../.env
      ../../.env.${TARGET}
    build:
      context: ../../
      dockerfile: infra/docker/idilic.dockerfile
      target: ${TARGET}

  server:
    image: ${REPO}/${PROJECT}.server:${TAG}
    restart: always
    env_file:
      ../../.env
      ../../.env.${TARGET}
    build:
      context: ../../
      dockerfile: infra/docker/server.dockerfile
      target: ${TARGET}

  database:
    command: ['mysqld', '--character-set-server=utf8mb4']
    image: mariadb:10.4.8-bionic
    restart: always
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER:     ${IDS_DATABASES_MAIN_USERNAME}
      MYSQL_PASSWORD: ${IDS_DATABASES_MAIN_PASSWORD}
      MYSQL_DATABASE: ${IDS_DATABASES_MAIN_DATABASE}
      MYSQL_PORT:     ${IDS_DATABASES_MAIN_PORT}

volumes:
  schema:
    driver: local
