version: '2.4'

services:

  server:
    image: ${REPO}/ids.server:${TAG}
    restart: always
    env_file:
      ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/server.dockerfile
      target: ${TARGET}
    volumes:
      - ../../:/app
      - /tmp:/tmp
    environment:
      DHOST_IP: ${DHOST_IP}
      XDEBUG_CONFIG: >
        remote_host=${DHOST_IP}
        remote_port=${XDEBUG_CONFIG_REMOTE_PORT}
        remote_handler=${XDEBUG_CONFIG_REMOTE_HANDLER}
        remote_enable=${XDEBUG_CONFIG_REMOTE_ENABLE}
        remote_log=${XDEBUG_CONFIG_REMOTE_LOG}

  idilic:
    image: ${REPO}/ids.idilic:${TAG}
    restart: on-failure
    env_file:
      ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/idilic.dockerfile
      target: ${TARGET}
    volumes:
      - ../../:/app
      - /tmp:/tmp
    environment:
      DHOST_IP: ${DHOST_IP}

  database:
    image: mariadb:10.4.8-bionic
    restart: always
    volumes:
      - schema:/var/lib/mysql
    environment:
      MYSQL_USER:          test
      MYSQL_PASSWORD:      test
      MYSQL_DATABASE:      ids_schema
      MYSQL_ROOT_PASSWORD: test
    command: ['mysqld', '--character-set-server=utf8mb4']

volumes:
  schema:
    driver: "local"



  # idilic:
  #   image: ${REPO}/ids.idilic:${TAG}
  #   build:
  #     context: ../../
  #     dockerfile: infra/docker/idilic.dockerfile
  #   restart: on-failure
  #   volumes:
  #     - ../../:/app
  #     - /tmp:/tmp
