version: '2.4'

services:

  idilic:
    extends:
      file: base.yml
      service: idilic
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    ports: ['80:80']
    extends:
      file: base.yml
      service: server
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['9996:3306']
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
