version: '2.4'

services:

  idilic:
    volumes: ['../../:/app', '/tmp:/tmp']
    depends_on: [database]
    extends:
      file: base.yml
      service: idilic
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    volumes: ['../../:/app', '/tmp:/tmp']
    ports:   ['${IDS_EXPOSE_HTTP}:80']
    depends_on: [database]
    extends:
      file: base.yml
      service: server
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['${IDS_EXPOSE_SQL}:${IDS_DATABASES_MAIN_PORT}']
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
