version: '2.4'

services:

  idilic:
    extends:
      file: base.yml
      service: idilic
    volumes: ['${OUTROOTDIR}/:/app']
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    volumes: ['${OUTROOTDIR}:/app']
    ports:   ['${IDS_EXPOSE_HTTP:-0}:8080']
    extends:
      file: base.yml
      service: server
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['${IDS_EXPOSE_SQL:-0}:${IDS_DATABASES_MAIN_PORT:-3306}']
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
