version: '2.4'

services:

  idilic:
    volumes: ['${OUTROOTDIR}/:/app']
    depends_on: [database]
    extends:
      file: base.yml
      service: idilic
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  phpfpm:
    volumes:
      - ${OUTROOTDIR}:/app
      - ${CORERELDIR}../../infra/php/www.conf:/etc/php/${PHP}/fpm/pool.d/www.conf
    extends:
      file: base.yml
      service: phpfpm
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  server:
    volumes: ['${OUTROOTDIR}:/app']
    ports:   ['${IDS_EXPOSE_HTTP:-0}:8080']
    extends:
      file: base.yml
      service: server
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  nginx:
    volumes:
      - ${OUTROOTDIR}:/app
      - ${CORERELDIR}../../infra/nginx/http.conf:/etc/nginx/conf.d/default.conf
    ports:   ['7777:80']
    extends:
      file: base.yml
      service: nginx
    depends_on: [database]
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DHOST_IP: ${DHOST_IP}

  database:
    ports: ['${IDS_EXPOSE_SQL:-0}:${IDS_DATABASES_MAIN_PORT:-3306}']
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
