version: '2.4'

services:

  idilic:
    volumes: ['../../:/app']
    extends:
      file: base.yml
      service: idilic
    depends_on: [database]

  server:
    ports: ['${IDS_EXPOSE_HTTP}:80']
    volumes: ['../../:/app']
    extends:
      file: base.yml
      service: server
    depends_on: [database]

  database:
    ports: ['${IDS_EXPOSE_SQL}:3306']
    extends:
      file: base.yml
      service: database

volumes:
  schema:
    driver: local
