version: '2.4'

x-aptcached:
  depends-on:
    - aptcache

services:

  aptcache:
    networks:
        - bridge
    restart: always
    image:   ${REPO}/${PROJECT}.aptcache:${TAG}
    build:
      context: ../../
      dockerfile: ${REALDIR}infra/docker/tools/aptcache.___gen.dockerfile
    volumes:
      - ${OUTMAKEDIR}:/app
      - ${OUTMAKEDIR}infra/apt/cache/:/var/cache/apt-cacher-ng

networks:
  bridge: {}
