version: '2.4'

x-aptcached:
  depends-on:
    - aptcache

services:

  aptcache:
    networks:
        - bridge
    restart: always
    build:
      context: ../../
      dockerfile: ${REALDIR}infra/docker/tools/aptcache.___gen.dockerfile
    volumes:
      - ../../:/app
      - ../../infra/apt/cache/:/var/cache/apt-cacher-ng

networks:
  bridge: {}
