version: '2.4'

services:

  cloc:
    restart: always
    image:   ${REPO}/${PROJECT}.cloc:${TAG}
    user:    ${D_UID}:${D_GID}
    build:
      context: ../../
      dockerfile: ${COREDIR}infra/docker/tools/cloc.___gen.dockerfile
    volumes:
      - ${OUTROOTDIR}:/app
