version: '2.4'

services:

  inotify:
    restart:    on-failure
    image:      ${REPO}/${PROJECT}.inotify:${TAG}
    command:    exit 0
    user:       ${D_UID}:${D_GID}
    build:
      context: ../../
      dockerfile: ${COREDIR}infra/docker/tools/inotify.___gen.dockerfile
    volumes:
      - ${OUTMAKEDIR}:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:${DOCKER}
