version: '2.4'

services:

  inotify:
    restart:     always
    build:
      context: ../../../
      dockerfile: ${REALDIR}infra/docker/tools/inotify.___gen.dockerfile
    volumes:
      - ../../../:/app
