version: '2.4'

services:

  node:
    restart: on-failure
    build:
      context: ../../
      dockerfile: ${REALDIR}/infra/docker/tools/node.dockerfile
    volumes:
      - ../../:/app
      - ../../vendor/_node_modules:/build/node_modules
