version: '2.4'

services:

  node:
    restart: on-failure
    image:   ${REPO}/${PROJECT}.node:${TAG}
    user:    ${D_UID}:${D_GID}
    build:
      context: ../../
      dockerfile: ${REALDIR}/infra/docker/tools/node.dockerfile
    volumes:
      - ../../:/app
      - ../../vendor/_node_modules:/build/node_modules
      - ../../package-lock.json:/build/package-lock.json

  npm:
    restart: on-failure
    image:   ${REPO}/${PROJECT}.node:${TAG}
    volumes:
      - ../../:/app
      - ../../vendor/_node_modules:/build/node_modules
      - ../../package-lock.json:/build/package-lock.json
    environment:
      IDS_NPM_ACTION: ${IDS_NPM_ACTION:-i}
    command: |
      - cp -n /app/composer.json /build/composer.json;
      - cp -n /app/package-lock.json /build;
      - cat package.json;
      - npm ${IDS_NPM_ACTION:-i};
      - cat package.json;
      - cp -n /build /app/package-lock.json;
      - cp -n /app/composer.json /build/composer.json;
      - echo "Done!";
