version: '2.4'

services:

  yjq:
    restart: always
    image:   ${REPO}/${PROJECT}.yjq:${TAG}
    user:    ${D_UID}:${D_GID}
    build:
      context: ../../../
      dockerfile: ${COREDIR}infra/docker/tools/yjq.dockerfile
    volumes:
      - ${OUTROOTDIR}:/app
