#!/usr/bin/env php
<?php
ini_set('display_errors', TRUE);
$_SERVER['HTTP_HOST'] = 'test.dev';
chdir(dirname(__FILE__));

$composer = require '../init.php';

use \SeanMorris\Ids\Path;
use \SeanMorris\Ids\Router;

use \SeanMorris\Ids\Idilic\Route\RootRoute;

foreach($argv as $arg)
{
	if(!preg_match('/^--?/', $arg))
	{
		$args[] = $arg;
	}
}

array_shift($args);

$request = new \SeanMorris\Ids\Request([
	'path' => $path = new Path(...$args)
]);
$routes = new RootRoute;
$router = new Router($request, $routes);
$router->contextSet('composer', $composer);

$res = $router->route();

if(!is_scalar($res) && $res !==  null)
{
	print json_encode($res, JSON_PRETTY_PRINT);
}
else
{
	print $res;
}

print PHP_EOL;
